# Generated by Django 2.2.13 on 2021-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210110_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('n', 'Not Requested For Approval'), ('p', 'Approval Application on Pending'), ('d', 'Approval Request Declined'), ('a', 'Verified')], max_length=2),
        ),
    ]
