# Generated by Django 2.2.13 on 2021-01-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210110_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('s', 'Subscriber'), ('s', 'Student'), ('t', 'Teacher'), ('e', 'Editor'), ('c', 'Academic Officer'), ('a', 'Admin')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('n', 'Not Requested For Approval'), ('p', 'Approval Application on Pending'), ('d', 'Approval Request Declined'), ('a', 'Verified')], default='n', max_length=2),
        ),
    ]
