# Generated by Django 4.2.3 on 2024-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_commonuserprofile_show_headline_in_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('n', 'Not Requested For Approval'), ('p', 'Approval Application is Pending'), ('d', 'Approval Request Declined'), ('a', 'Verified')], default='n', max_length=2),
        ),
    ]
