# Generated by Django 4.2 on 2026-09-20 20:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='show_headline_in_bio',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='commonuserprofile',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
