# Generated by Django 4.2 on 2026-09-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_dead_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuserprofile',
            name='social_links',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
