# Generated by Django 2.2.13 on 2021-02-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssladmissionpaymentverfication',
            options={'ordering': ['-created'], 'verbose_name_plural': 'SSL Admission Payment Verfication'},
        ),
        migrations.AlterModelOptions(
            name='sslpayment',
            options={'ordering': ['-created', 'received_amount'], 'verbose_name_plural': 'SSL Payment'},
        ),
    ]
