# Generated by Django 4.2.3 on 2023-07-08 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20210227_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssladmissionpaymentverfication',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_pay_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
