# Generated by Django 2.2.7 on 2019-11-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_auto_20191108_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('establish_date', models.DateField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('guide', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('roll', models.CharField(max_length=6, unique=True)),
                ('registration_number', models.CharField(max_length=6, unique=True)),
                ('mobile', models.CharField(max_length=11)),
                ('guardian_mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('last_gpa', models.FloatField()),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.AcademicSession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Department')),
                ('semester', models.ForeignKey(default='1st', on_delete=django.db.models.deletion.CASCADE, to='students.Semester')),
            ],
        ),
    ]
