# Generated by Django 2.2.7 on 2019-11-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_tools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='studentavar.png', upload_to='students')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('roll', models.CharField(max_length=6, unique=True)),
                ('registration_number', models.CharField(max_length=6, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_gpa', models.FloatField(blank=True, null=True)),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.AcademicSession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.Department')),
                ('semester', models.ForeignKey(default='1st', on_delete=django.db.models.deletion.CASCADE, to='admin_tools.Semester')),
            ],
            options={
                'ordering': ['semester', 'roll', 'registration_number'],
            },
        ),
    ]
