# Generated by Django 2.2.13 on 2020-10-06 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_by',
            new_name='admitted_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department_choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(default='', max_length=100, verbose_name="Father's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_exam_name',
            field=models.CharField(choices=[('HSC', 'Higher Secondary Certificate'), ('SSC', 'Secondary School Certificate'), ('DAKHIL', 'Dakhil Exam'), ('JDC', 'Junior Dakhil Certificate')], default='', max_length=2, verbose_name='Last Exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_exam_registration',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_exam_result',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_exam_roll',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='', max_length=11, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(default='', max_length=100, verbose_name="Mother's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.AcademicSession'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Birth Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/applicant/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Semester'),
        ),
        migrations.CreateModel(
            name='AdmissionStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='students/applicant/')),
                ('fathers_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mothers_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('date_of_birth', models.DateField(verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('mobile_number', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('last_exam_name', models.CharField(choices=[('HSC', 'Higher Secondary Certificate'), ('SSC', 'Secondary School Certificate'), ('DAKHIL', 'Dakhil Exam'), ('JDC', 'Junior Dakhil Certificate')], max_length=2, verbose_name='Last Exam')),
                ('last_exam_roll', models.CharField(max_length=10)),
                ('last_exam_registration', models.CharField(max_length=10)),
                ('last_exam_result', models.CharField(max_length=5)),
                ('department_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
