# Generated by Django 2.2.7 on 2019-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191113_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.PositiveIntegerField(max_length=4, unique=True),
        ),
    ]
