# Generated by Django 2.2.7 on 2019-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191113_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
