# Generated by Django 2.2.7 on 2019-11-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20191129_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['semester', 'roll', 'registration_number']},
        ),
    ]
