# Generated by Django 2.2.7 on 2019-12-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20191129_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_gpa',
        ),
    ]
