# Generated by Django 2.2.13 on 2020-12-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20201204_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='application_type',
            field=models.CharField(choices=[('1', 'Online'), ('2', 'Offline')], default='1', max_length=1),
        ),
    ]
