# Generated by Django 2.2.13 on 2020-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_admissionstudent_assigned_as_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='counsel_comment',
            field=models.ManyToManyField(blank=True, to='students.CounselingComment'),
        ),
    ]
