# Generated by Django 2.2.13 on 2020-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_subject_book_cover'),
        ('students', '0021_student_temporary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ac_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.AcademicSession'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.Semester'),
            preserve_default=False,
        ),
    ]
