# Generated by Django 2.2.13 on 2021-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20201226_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='\n        এই মর্মে অঙ্গীকার করছি যে, ভর্তি হওয়ার সুযোগ পেলে আমি অত্র শিক্ষা প্রতিষ্ঠানের যাবতীয় আইনকানুন মেনে চলব এবং \n        কোন অবস্থাতেই অত্র শিক্ষা প্রতিষ্ঠান এবং দেশের আইনের পরিপন্থি কোন কাজে লিপ্ত হব না \n        '),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='marksheet_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/applicants/marksheets/', verbose_name='Upload Your Marksheet'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nid_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/applicants/nid_cards/', verbose_name='Upload Your NID Card'),
        ),
    ]
