# Generated by Django 2.2.13 on 2021-01-25 08:51

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210125_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, to='articles.Category'),
        ),
    ]
