# Generated by Django 2.2.13 on 2021-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_on_menu',
            field=models.BooleanField(default=False),
        ),
    ]
