# Generated by Django 2.2.13 on 2021-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='force_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
