# Generated by Django 2.2.13 on 2021-02-27 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
