# Generated by Django 2.2.13 on 2021-01-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210125_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Category'),
        ),
    ]
