# Generated by Django 2.2.13 on 2021-01-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210125_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
