# Generated by Django 2.2.13 on 2021-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210301_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
