# Generated by Django 2.2.13 on 2021-03-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_blogconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogconfiguration',
            name='theme_name',
            field=models.CharField(choices=[('tw', 'tailwind'), ('bs4', 'bootstrap4-rm')], default='bs4', max_length=5),
        ),
    ]
