# Generated by Django 2.2.13 on 2022-04-27 19:02

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20210325_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, to='articles.Category'),
        ),
    ]
