# Generated by Django 2.2.7 on 2019-12-13 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20191129_0634'),
        ('teachers', '0006_auto_20191129_0418'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 13, 17, 23, 44, 495158)),
        ),
        migrations.CreateModel(
            name='CourseAssignToTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='course.Course')),
                ('teacher', models.ManyToManyField(to='teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignToStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='course.Course')),
                ('student', models.ManyToManyField(to='students.Student')),
            ],
        ),
    ]
