# Generated by Django 2.2.7 on 2019-12-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20191129_0634'),
        ('teachers', '0006_auto_20191129_0418'),
        ('course', '0002_auto_20191213_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseattendance',
            name='total_attendance',
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='student',
            field=models.ManyToManyField(to='students.Student'),
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='teacher',
            field=models.ManyToManyField(to='teachers.Teacher'),
        ),
        migrations.RemoveField(
            model_name='courseattendance',
            name='course',
        ),
        migrations.AddField(
            model_name='courseattendance',
            name='course',
            field=models.ManyToManyField(to='course.Course'),
        ),
        migrations.AlterField(
            model_name='courseattendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 13, 18, 12, 51, 30627)),
        ),
    ]
