# Generated by Django 2.2.7 on 2019-12-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191213_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
