# Generated by Django 2.2.7 on 2019-12-13 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191213_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 13, 19, 43, 17, 632460)),
        ),
    ]
