# Generated by Django 2.2.13 on 2020-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201009_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='counsel_comment',
            field=models.ManyToManyField(blank=True, null=True, to='teachers.Teacher'),
        ),
    ]
