# Generated by Django 2.2.13 on 2020-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20201009_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='last_exam_name',
            field=models.CharField(choices=[('HSC', 'Higher Secondary Certificate'), ('SSC', 'Secondary School Certificate'), ('DAKHIL', 'Dakhil Exam'), ('JDC', 'Junior Dakhil Certificate')], max_length=10, verbose_name='Last Exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_exam_name',
            field=models.CharField(choices=[('HSC', 'Higher Secondary Certificate'), ('SSC', 'Secondary School Certificate'), ('DAKHIL', 'Dakhil Exam'), ('JDC', 'Junior Dakhil Certificate')], max_length=10, verbose_name='Last Exam'),
        ),
    ]
