# Generated by Django 2.2.13 on 2020-10-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_admissionstudent_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
