# Generated by Django 2.2.13 on 2020-12-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20201208_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department_choice',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_exam_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_exam_registration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_exam_result',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_exam_roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
