# Generated by Django 2.2.13 on 2020-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20201208_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='assigned_as_student',
            field=models.BooleanField(default=False),
        ),
    ]
