# Generated by Django 2.2.13 on 2020-12-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20201219_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='choosen_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_students', to='academics.Department'),
        ),
    ]
