# Generated by Django 2.2.13 on 2021-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20210223_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstudent',
            name='board',
            field=models.CharField(default='Dhaka', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='group',
            field=models.CharField(default='Science', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='ssc_roll',
            field=models.CharField(default='0001', max_length=10),
            preserve_default=False,
        ),
    ]
