# Generated by Django 2.2.13 on 2021-03-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20210316_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselingcomment',
            options={'ordering': ['-created']},
        ),
    ]
