# Generated by Django 4.2.3 on 2023-07-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_admissionstudent_id_alter_counselingcomment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='In publishing and graphic design, \n                                  Lorem ipsum is a placeholder text commonly used'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='exam_name',
            field=models.CharField(choices=[('HSC', 'Higher Secondary Certificate'), ('SSC', 'Secondary School Certificate'), ('DAKHIL', 'Dakhil Exam'), ('VOCATIONAL', 'Vocational')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='guardian_mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
    ]
