from enum import Enum


class AcademicsURLEnum(Enum):
    all_semester = 'semesters/'
    departments = 'departments/'
    create_department = 'create-department/'
    create_semester = 'create-semester/'
    create_academic_session = 'create-academic-session/'
    create_subject = 'create-subject'
    delete_dept = 'depts/delete/<int:pk>/'
    academic_sessions = 'academic_sessions/'
    update_department = 'department/update/<int:pk>/'
    subject_list = 'subjects/'
    import_subject_csv = 'upload-subjects-csv/'
    create_batch = 'create-batch/'
    batch_list = 'batch-list/'
    update_subject = 'subjects/update/<int:pk>/'
    delete_subject = 'subjects/delete/<int:pk>/'
    update_academic_session = 'academic-sessions/update/<int:pk>/'
    delete_academic_session = 'academic-sessions/delete/<int:pk>/'
    update_batch = 'batches/update/<int:pk>/'
    delete_batch = 'batches/delete/<int:pk>/'
    update_semester = 'semesters/update/<int:pk>/'
    delete_semester = 'semesters/delete/<int:pk>/'


class AcademicsURLConstants:
    all_semester = f'academics:{AcademicsURLEnum.all_semester.name}'
    departments = f'academics:{AcademicsURLEnum.departments.name}'
    create_department = f'academics:{AcademicsURLEnum.create_department.name}'
    create_semester = f'academics:{AcademicsURLEnum.create_semester.name}'
    create_academic_session = f'academics:{AcademicsURLEnum.create_academic_session.name}'
    create_subject = f'academics:{AcademicsURLEnum.create_subject.name}'
    delete_dept = f'academics:{AcademicsURLEnum.delete_dept.name}'
    academic_sessions = f'academics:{AcademicsURLEnum.academic_sessions.name}'
    update_department = f'academics:{AcademicsURLEnum.update_department.name}'
    subject_list = f'academics:{AcademicsURLEnum.subject_list.name}'
    import_subject_csv = f'academics:{AcademicsURLEnum.import_subject_csv.name}'
    create_batch = f'academics:{AcademicsURLEnum.create_batch.name}'
    batch_list = f'academics:{AcademicsURLEnum.batch_list.name}'
    update_subject = f'academics:{AcademicsURLEnum.update_subject.name}'
    delete_subject = f'academics:{AcademicsURLEnum.delete_subject.name}'
    update_academic_session = f'academics:{AcademicsURLEnum.update_academic_session.name}'
    delete_academic_session = f'academics:{AcademicsURLEnum.delete_academic_session.name}'
    update_batch = f'academics:{AcademicsURLEnum.update_batch.name}'
    delete_batch = f'academics:{AcademicsURLEnum.delete_batch.name}'
    update_semester = f'academics:{AcademicsURLEnum.update_semester.name}'
    delete_semester = f'academics:{AcademicsURLEnum.delete_semester.name}'
