# Generated by Django 2.2.13 on 2021-01-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210110_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('s', 'Subscriber'), ('st', 'Student'), ('t', 'Teacher'), ('e', 'Editor'), ('c', 'Academic Officer'), ('a', 'Admin')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Editor', 'Editor'), ('academicoficer', 'Academic Officer'), ('admin', 'Admin')], default='subscriber', max_length=50),
        ),
    ]
