# Generated by Django 2.2.13 on 2021-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210116_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('student', 'Student'), ('teacher', 'Teacher'), ('editor', 'Editor'), ('academic_oficer', 'Academic Officer'), ('admin', 'Admin')], default='subscriber', max_length=50),
        ),
    ]
