# Generated by Django 2.2.13 on 2021-01-28 11:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-pictures')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='cover-pictures')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('show_headline_in_bio', models.BooleanField(default=False, help_text='I want to use this as my bio')),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Your Profile Summary', null=True)),
                ('social_links', models.ManyToManyField(blank=True, related_name='social_links', to='accounts.SocialLink')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
