# Generated by Django 2.2.7 on 2019-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['joining_date', 'name']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='teacheravatar.jpg', upload_to='teachers'),
        ),
    ]
