# Generated by Django 2.2.13 on 2020-12-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_auto_20201219_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='book_cover',
            field=models.ImageField(default='subjects/bookcover.png', upload_to='subjects/'),
        ),
    ]
