# Generated by Django 4.2.3 on 2024-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_academicsession_id_alter_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='practical_marks',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_marks',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
