# Generated by Django 2.2.13 on 2021-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateField(auto_now=True),
        ),
    ]
