# Generated by Django 2.2.13 on 2021-02-04 16:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20210126_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprofile',
            name='motto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
