# Generated by Django 4.2.3 on 2023-07-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_alter_instituteprofile_id_alter_listwidget_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituteprofile',
            old_name='index_title',
            new_name='super_admin_index_title',
        ),
    ]
