# Generated by Django 4.2.3 on 2025-01-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_designation_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(default=111111, max_length=50),
            preserve_default=False,
        ),
    ]
