# Generated by Django 2.2.13 on 2021-04-06 06:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_noticedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notfiy_groups',
            field=models.ManyToManyField(blank=True, related_name='notfied_notices', to='notices.NotifyGroup'),
        ),
        migrations.AlterField(
            model_name='noticedocument',
            name='file',
            field=models.FileField(upload_to='files/notices/', verbose_name='Notice PDF Document'),
        ),
    ]
