# Generated by Django 2.2.13 on 2020-10-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201006_0201'),
        ('result', '0002_auto_20201006_0201'),
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='guide',
        ),
        migrations.AlterUniqueTogether(
            name='semestercombination',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='semestercombination',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='semestercombination',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='semestercombination',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semestercombination',
            name='semester',
        ),
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='SemesterCombination',
        ),
    ]
