# Generated by Django 2.2.7 on 2019-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
