# Generated by Django 2.2.7 on 2019-11-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0002_auto_20191127_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.AcademicSession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.Semester')),
            ],
        ),
    ]
