# Generated by Django 2.2.7 on 2019-11-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0003_semestercombination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestercombination',
            options={'ordering': ['semester', 'department']},
        ),
        migrations.AlterUniqueTogether(
            name='semestercombination',
            unique_together={('department', 'semester')},
        ),
    ]
