# Generated by Django 2.2.7 on 2019-11-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0004_auto_20191129_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestercombination',
            options={'ordering': ['department', 'semester']},
        ),
    ]
