# Generated by Django 2.2.13 on 2021-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_instituteprofile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='index_title',
            field=models.CharField(default='Django-School-Management Admin', help_text='Will be displayed in SuperAdmin dashboard listing pages', max_length=100),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='site_header',
            field=models.CharField(default='Django-School-Management', help_text='Will be displayed in SuperAdmin Dashboard', max_length=100),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='site_title',
            field=models.CharField(default='Welcome to the Django-School-Management', help_text='Title of the application/site', max_length=100),
        ),
    ]
