# Generated by Django 2.2.13 on 2020-12-06 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.PositiveIntegerField(verbose_name='Batch Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.AcademicSession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
