# Generated by Django 2.2.13 on 2020-12-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
    ]
