# Generated by Django 2.2.13 on 2020-12-08 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_admissionstudent_rejected'),
        ('academics', '0004_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='batches',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_batches', to='academics.Batch'),
        ),
        migrations.AddField(
            model_name='department',
            name='current_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_batches', to='academics.Batch'),
        ),
        migrations.CreateModel(
            name='TempSerialID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_serials', to='academics.Department')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.AcademicSession')),
            ],
            options={
                'unique_together': {('department', 'year', 'serial')},
            },
        ),
    ]
