# Generated by Django 2.2.13 on 2020-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20201208_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='batches',
            field=models.ManyToManyField(related_name='department_batches', to='academics.Batch'),
        ),
    ]
