# Generated by Django 2.2.13 on 2020-12-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20201208_0801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempserialid',
            unique_together=set(),
        ),
    ]
