# Generated by Django 2.2.13 on 2020-12-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_auto_20201208_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('year', 'department', 'number')},
        ),
    ]
