# Generated by Django 2.2.13 on 2020-12-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_auto_20201208_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempserialid',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_serial', to='students.Student'),
        ),
    ]
