# Generated by Django 2.2.13 on 2021-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_auto_20210118_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='department_batches', to='academics.Batch'),
        ),
    ]
