# Generated by Django 2.2.13 on 2021-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_auto_20210124_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_icon',
            field=models.ImageField(blank=True, help_text='Upload an image/icon for the department', null=True, upload_to='department_icon/'),
        ),
        migrations.AddField(
            model_name='department',
            name='short_description',
            field=models.TextField(blank=True, help_text='Write short description about the department.', null=True),
        ),
    ]
